export DOTFILES="$HOME/git/dotfiles"

source $DOTFILES/system/env
source $DOTFILES/system/path
source $DOTFILES/system/alias

source $ZSH/oh-my-zsh.sh
source $DOTFILES/zsh/plugins.zsh
source $DOTFILES/zsh/prompt.zsh
autoload -U compinit && compinit


source $HOME/.config/lf/LF_ICONS
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
